#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Nxu\Nap56\Commands\Install());
$application->add(new \Nxu\Nap56\Commands\AddSite());

$application->run();
